### ISSUE TITLE
Use the dynamo table name attribute when present 

### ISSUE THREAD

**Issue by vespertilian** [wassilygraf/testify-dynamodb#10]
Hey, 

This is a super helpful util so thanks!. I just created a PR that uses the table name attribute if it's present.

**Comment by wassilygraf** [comment]
Glad you find it useful! thanks for the PR - merged it!

**Comment by vespertilian** [comment]
Thanks for the merge,

Are you happy to also to deploy to NPM? Not sure if you should go 1.1.0 or 2.0.0, as my change *might break people who are relying on the resource name instead of the table name.
